//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hablame.Repositories.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MistakeMadeMistakeType
    {
        public System.Guid Id { get; set; }
        public System.Guid ConversationId { get; set; }
        public System.Guid MistakeTypeId { get; set; }
    }
}
