//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hablame.Repositories.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConversationSummary
    {
        public System.DateTime StartDateTime { get; set; }
        public string ConfigurationName { get; set; }
        public int DurationMinutes { get; set; }
        public System.Guid LanguageId { get; set; }
        public System.Guid MistakeTypeOptionsConfigId { get; set; }
        public string StudentForename { get; set; }
        public string StudentSurname { get; set; }
        public string TeacherForename { get; set; }
        public string TeacherSurname { get; set; }
        public string Language { get; set; }
        public System.Guid ConversationId { get; set; }
        public System.Guid StudentId { get; set; }
        public System.Guid TeacherId { get; set; }
    }
}
